# db_setup/Dockerfile_CassandraSetup
FROM python:3.9-slim-buster

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY cassandra_setup.py .

CMD ["python", "cassandra_setup.py"]