# dashboard/Dockerfile_Dashboard
FROM python:3.9-slim-buster
WORKDIR /app

# Copy requirements.txt (now relative to project root)
COPY dashboard/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the Streamlit app (now relative to project root)
COPY dashboard/app.py .

EXPOSE 8501
ENTRYPOINT ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]